### PR TITLE
Fix failing spec caused by Java Event to_hash differences

### PR DESCRIPTION
**Pull request by guyboertje**
With the new java event the to_hash function returns different instances each time. The timestamp field will 'inspect' to a different string each time `to_hash` is called.

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jsvd** [comment]
when is this necessary? I'm looking at master and there are no object references in the awesome_inspect:

```
1.9 :007 > require 'awesome_print'
 => false 
1.9 :008 > e = LogStash::Event.new("hey"=> 1, "init_ts" => LogStash::Timestamp.now)
 => 2017-01-10T10:56:47.012Z %{host} %{message} 
1.9 :009 > e.to_hash.awesome_inspect == e.to_hash.awesome_inspect
 => true 
```

**Comment by guyboertje** [comment]
Maybe it is  JRuby 9K specific, let me check.

**Comment by guyboertje** [comment]
On a fresh zip download of LS master with 1.7.25 this problem does not occur - it must be JRuby 9K specific.
I think, in 1.7.25 awesome_inspect and therefore inspect will call to_s because the result shows the Timestamp as an iso8601 string.
In 9K it shows the instance inspect as in `<#LogStash::Timestamp:0xabcdef1>`

Meaning that this fix will work for both 1.7.25 and 9.1.6.0

**Comment by jsvd** [comment]
@guyboertje instead of patching this plugin should we address this at core level? other plugins/core code may suffer from this 9k behaviour:

```
% rvm use jruby-1.7.25; bundle exec ruby -e "require 'logstash-core'; require 'logstash/event'; puts LogStash::Timestamp.now.inspect"
2017-01-10T12:18:37.495Z
% rvm use jruby-9.1.2.0; bundle exec ruby -e "require 'logstash-core'; require 'logstash/event'; puts LogStash::Timestamp.now.inspect"
Using /Users/joaoduarte/.rvm/gems/jruby-9.1.2.0
#<LogStash::Timestamp:0x26f46fa6>
```

**Comment by guyboertje** [comment]
Address in core - closing

**Pull request closed without merging**
